language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls
