language: python
python:
  - "3.6"
install:
  - pip install requests
  - pip install pytest
  - pip install python-coveralls
  - pip install coverage       # Add me to install coverage.py
  - pip install nose           # Add me to install nose
script:
  - pytest
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls
